set(XQ_PLUGINS
    org.xq.core.application:ON
    org.xq.data.projectnodes:ON
    org.xq.data.pythonnodes:ON
    org.xq.core.datamanager:ON
    org.xq.core.workspace:ON
    org.xq.pipeline.vesselplanning:ON
    org.xq.pipeline.lumencontouring:ON
    org.xq.pipeline.contouring3d:ON
    org.xq.pipeline.vascularmodeling:ON
    org.xq.pipeline.gridgeneration:ON
    org.xq.pipeline.hemodynamics:ON
)
