if(NOT DEFINED XQ_STAGE_RUNTIME_DESTINATION)
  message(FATAL_ERROR "XQ_STAGE_RUNTIME_DESTINATION is required")
endif()

if(NOT DEFINED XQ_STAGE_RUNTIME_DIRS)
  message(FATAL_ERROR "XQ_STAGE_RUNTIME_DIRS is required")
endif()

file(MAKE_DIRECTORY "${XQ_STAGE_RUNTIME_DESTINATION}")

if(DEFINED XQ_STAGE_RUNTIME_FILES)
  foreach(_runtime_file IN LISTS XQ_STAGE_RUNTIME_FILES)
    if(EXISTS "${_runtime_file}")
      file(COPY "${_runtime_file}" DESTINATION "${XQ_STAGE_RUNTIME_DESTINATION}")
    endif()
  endforeach()
endif()

foreach(_runtime_dir IN LISTS XQ_STAGE_RUNTIME_DIRS)
  if(IS_DIRECTORY "${_runtime_dir}")
    file(GLOB _runtime_dlls "${_runtime_dir}/*.dll")
    foreach(_runtime_dll IN LISTS _runtime_dlls)
      file(COPY "${_runtime_dll}" DESTINATION "${XQ_STAGE_RUNTIME_DESTINATION}")
    endforeach()
  endif()
endforeach()

if(DEFINED XQ_STAGE_QT_PLUGINS_DIR AND IS_DIRECTORY "${XQ_STAGE_QT_PLUGINS_DIR}/platforms")
  file(MAKE_DIRECTORY "${XQ_STAGE_RUNTIME_DESTINATION}/platforms")
  file(GLOB _qt_platform_plugins "${XQ_STAGE_QT_PLUGINS_DIR}/platforms/*.dll")
  foreach(_qt_platform_plugin IN LISTS _qt_platform_plugins)
    file(COPY "${_qt_platform_plugin}" DESTINATION "${XQ_STAGE_RUNTIME_DESTINATION}/platforms")
  endforeach()
endif()
